apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keep-running-preemptive
  name: keep-running-preemptive
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keep-running-preemptive
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keep-running-preemptive
        restart: "0"
    spec:
      containers:
      - image: yourRegistry:master-v0.0.3
        imagePullPolicy: IfNotPresent
        name: keep-running-preemptive
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30